name: Publish

on:
  push:
    branches: master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with dotnet
      run: dotnet build NetworkConnection/NetworkConnection.csproj --configuration Release
    - name: Pack Nuget
      run: dotnet pack NetworkConnection/NetworkConnection.csproj -o . -c Release -p:PackageVersion=1.0.$env:GITHUB_RUN_NUMBER --version-suffix $env:GITHUB_SHA
    - name: Publish nuget to Nuget.org
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
    - name: Publish nuget to Github
      run: |
        sed 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' .nuget/.nuget.config > nuget.config
        dotnet nuget push "*.nupkg" -s "github"
