name: Publish

on:
  push:
    branches: master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build NetworkConnection/NetworkConnection.csproj --configuration Release
    - name: Pack Nuget
      run: dotnet pack NetworkConnection/NetworkConnection.csproj -o . -c Release --include-source -p:PackageVersion=1.0.$GITHUB_RUN_NUMBER --version-suffix $GITHUB_SHA
    - name: Publish nuget to Nuget.org
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
